### ISSUE TITLE
Delete users - Add the ability to delete users based on registration date

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#322]
@mariadanieldeepak 

For now just do a research on it to find out what needs to be done.

Don't start the implementation yet.

**Comment by mariadanieldeepak** [comment]
@sudar,

Following are my observations and could be turned in to implementation steps.

- User registration date is stored in WP_Users table in `user_registered DATETIME` column. Refer [ER](https://codex.wordpress.org/images/2/25/WP4.4.2-ERD.png) diagram.
- The User registration date can be queried using [WP_User_Query](https://codex.wordpress.org/Class_Reference/WP_User_Query). We can support the following filters - `after`, `before`, `equals`, time in natural language (ex. `x` hours ago) and also a date range. Multiple date ranges could also be supported, though this needs a bit of research.
- We can take advantage of `date_query ` but that will enforce us to support **WordPress v4.1** or **later**. Currently we also support v4.0.

The task involves 

- [ ] Adding a module to the Delete Users page
- [ ] Replicating a existing User module
- [ ] Modifying the `convert_user_input_to_options()` as required
- [ ] Since our existing implementation uses `WP_User_Query`, we may have to play with `date_query ` to retrieve Users based on `registration date`.

**Comment by sudar** [comment]
Closing this since we already have the filter to delete users based on registration date.
