### ISSUE TITLE
Delete Comment Meta - Rename label

### ISSUE THREAD

**Issue by rajanit2000** [sudar/bulk-delete#491]
UI shows `Restrict to posts which are Older | Post within last` 

![screenshot](https://user-images.githubusercontent.com/2988033/44241754-8c66de00-a1e3-11e8-869d-ddd1bf4ad883.png)

But date query only use by getting comments 

```
$op   = $options['date_op'];
$days = $options['days'];

if ( $options['restrict'] ) {
	$args['date_query'] = array(
		array(
			'column' => 'comment_date',
			$op      => "{$days} day ago",
		),
	);
}

if ( $options['use_value'] ) {
	$args['meta_query'] = apply_filters( 'bd_delete_comment_meta_query', array(), $options );
} else {
	$args['meta_key'] = $options['meta_key'];
}

$meta_deleted = 0;
$comments     = get_comments( $args );
```

**Comment by sudar** [comment]
@mariadanieldeepak 

Check if anything needs to be done for this.

**Comment by mariadanieldeepak** [comment]
@sudar,

@rajanit2000 has implied that the filter's label should be "Only restrict to **comments** which are " instead of "Only restrict to **posts** which are 

The following lines from my observation is to say that we're deleting Comments by retrieving Comments `date` column.

https://github.com/sudar/bulk-delete/blob/dev/6.0.0/include/Core/Metas/Modules/DeleteCommentMetaModule.php#L133

https://github.com/sudar/bulk-delete/blob/dev/6.0.0/include/Core/Metas/Modules/DeleteCommentMetaModule.php#L146

**Comment by sudar** [comment]
@esudalaimadan 

Change the label from "Only restrict to posts" to "Only restrict to comments which"
